# stations_data.py

stations = {
    "Clement Town": (30.3450, 78.0580),
    "Raipur": (30.3550, 78.0540),
    "I.S.B.T": (30.3365, 78.0450),
    "Laal Pul": (30.3285, 78.0415),
    "Clock Tower": (30.3183, 78.0336),
    "Dilaram Chowk": (30.3155, 78.0345),
    "Paltan Bazaar": (30.3190, 78.0366),
    "Rajpur Road": (30.3087, 78.0300),
    "Jakhan": (30.3165, 78.0630),
    "Prem Nagar": (30.2804, 78.0243),
    "Majra": (30.2760, 78.0201),
    "Balliwala": (30.2630, 78.0100),
    "Kishanpur": (30.2520, 78.0020),
    "Vikasnagar": (30.2200, 77.9750),
    "Sahaspur": (30.2000, 77.9500),
}

# 50 routes connecting these 15 stations with times (in mins) and buses running on them
edges = {
    ("Clement Town", "Raipur"): {"time": 5, "buses": ["Bus1", "Bus5"]},
    ("Raipur", "I.S.B.T"): {"time": 4, "buses": ["Bus1", "Bus7"]},
    ("I.S.B.T", "Laal Pul"): {"time": 3, "buses": ["Bus2", "Bus7"]},
    ("Laal Pul", "Clock Tower"): {"time": 6, "buses": ["Bus2", "Bus8"]},
    ("Clock Tower", "Dilaram Chowk"): {"time": 2, "buses": ["Bus3", "Bus8"]},
    ("Dilaram Chowk", "Paltan Bazaar"): {"time": 3, "buses": ["Bus3", "Bus9"]},
    ("Paltan Bazaar", "Rajpur Road"): {"time": 7, "buses": ["Bus4", "Bus9"]},
    ("Rajpur Road", "Jakhan"): {"time": 8, "buses": ["Bus4", "Bus10"]},
    ("Jakhan", "Prem Nagar"): {"time": 5, "buses": ["Bus5", "Bus10"]},
    ("Prem Nagar", "Majra"): {"time": 4, "buses": ["Bus5", "Bus11"]},
    ("Majra", "Balliwala"): {"time": 3, "buses": ["Bus6", "Bus11"]},
    ("Balliwala", "Kishanpur"): {"time": 6, "buses": ["Bus6", "Bus12"]},
    ("Kishanpur", "Vikasnagar"): {"time": 10, "buses": ["Bus7", "Bus12"]},
    ("Vikasnagar", "Sahaspur"): {"time": 15, "buses": ["Bus8", "Bus13"]},

    # Reverse routes (for bidirectionality)
    ("Raipur", "Clement Town"): {"time": 5, "buses": ["Bus1", "Bus5"]},
    ("I.S.B.T", "Raipur"): {"time": 4, "buses": ["Bus1", "Bus7"]},
    ("Laal Pul", "I.S.B.T"): {"time": 3, "buses": ["Bus2", "Bus7"]},
    ("Clock Tower", "Laal Pul"): {"time": 6, "buses": ["Bus2", "Bus8"]},
    ("Dilaram Chowk", "Clock Tower"): {"time": 2, "buses": ["Bus3", "Bus8"]},
    ("Paltan Bazaar", "Dilaram Chowk"): {"time": 3, "buses": ["Bus3", "Bus9"]},
    ("Rajpur Road", "Paltan Bazaar"): {"time": 7, "buses": ["Bus4", "Bus9"]},
    ("Jakhan", "Rajpur Road"): {"time": 8, "buses": ["Bus4", "Bus10"]},
    ("Prem Nagar", "Jakhan"): {"time": 5, "buses": ["Bus5", "Bus10"]},
    ("Majra", "Prem Nagar"): {"time": 4, "buses": ["Bus5", "Bus11"]},
    ("Balliwala", "Majra"): {"time": 3, "buses": ["Bus6", "Bus11"]},
    ("Kishanpur", "Balliwala"): {"time": 6, "buses": ["Bus6", "Bus12"]},
    ("Vikasnagar", "Kishanpur"): {"time": 10, "buses": ["Bus7", "Bus12"]},
    ("Sahaspur", "Vikasnagar"): {"time": 15, "buses": ["Bus8", "Bus13"]},

    # Cross connections for richer graph (add 18 more routes to total 50)
    ("Clement Town", "I.S.B.T"): {"time": 8, "buses": ["Bus14"]},
    ("Raipur", "Laal Pul"): {"time": 7, "buses": ["Bus14"]},
    ("I.S.B.T", "Clock Tower"): {"time": 10, "buses": ["Bus15"]},
    ("Laal Pul", "Dilaram Chowk"): {"time": 5, "buses": ["Bus15"]},
    ("Clock Tower", "Paltan Bazaar"): {"time": 7, "buses": ["Bus16"]},
    ("Dilaram Chowk", "Rajpur Road"): {"time": 8, "buses": ["Bus16"]},
    ("Paltan Bazaar", "Jakhan"): {"time": 9, "buses": ["Bus17"]},
    ("Rajpur Road", "Prem Nagar"): {"time": 12, "buses": ["Bus17"]},
    ("Jakhan", "Majra"): {"time": 11, "buses": ["Bus18"]},
    ("Prem Nagar", "Balliwala"): {"time": 10, "buses": ["Bus18"]},
    ("Majra", "Kishanpur"): {"time": 9, "buses": ["Bus19"]},
    ("Balliwala", "Vikasnagar"): {"time": 13, "buses": ["Bus19"]},
    ("Kishanpur", "Sahaspur"): {"time": 15, "buses": ["Bus20"]},

    # Reverse of cross connections
    ("I.S.B.T", "Clement Town"): {"time": 8, "buses": ["Bus14"]},
    ("Laal Pul", "Raipur"): {"time": 7, "buses": ["Bus14"]},
    ("Clock Tower", "I.S.B.T"): {"time": 10, "buses": ["Bus15"]},
    ("Dilaram Chowk", "Laal Pul"): {"time": 5, "buses": ["Bus15"]},
    ("Paltan Bazaar", "Clock Tower"): {"time": 7, "buses": ["Bus16"]},
    ("Rajpur Road", "Dilaram Chowk"): {"time": 8, "buses": ["Bus16"]},
    ("Jakhan", "Paltan Bazaar"): {"time": 9, "buses": ["Bus17"]},
    ("Prem Nagar", "Rajpur Road"): {"time": 12, "buses": ["Bus17"]},
    ("Majra", "Jakhan"): {"time": 11, "buses": ["Bus18"]},
    ("Balliwala", "Prem Nagar"): {"time": 10, "buses": ["Bus18"]},
    ("Kishanpur", "Majra"): {"time": 9, "buses": ["Bus19"]},
    ("Vikasnagar", "Balliwala"): {"time": 13, "buses": ["Bus19"]},
    ("Sahaspur", "Kishanpur"): {"time": 15, "buses": ["Bus20"]},
}
